spring:
    application:
      name: ccbb
    web:
      resources:
        static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
  # Database
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://34.47.85.142:5432/health
      username: health
      password: K8o#<iu]OjMG+0ka
  # jpa properties
    jpa:
      hibernate:
        ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
    data:
      redis:
        host: localhost
        port: 6379


server:
  port: 8081

#JWT
jwt:
  secret: qwrmlasfmlqw2491u4291urjeiqowfjkwklfnlksdnfi13fnou3nounf13
  expiration: 3600000  # 1 hour (밀리초 단위)